# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Olympus < Formula
  desc "AI orchestration layer for developers — multi-model, local-first, governance built-in"
  homepage "https://olympus.sh"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/convergent-systems-co/olympus-cli/releases/download/v0.1.0/olympus_0.1.0_darwin_amd64.tar.gz"
      sha256 "a1c0f124d4060ca2a848da5d24c733813b28864b48b9edc4771d8c97dd768e5f"

      define_method(:install) do
        bin.install "olympus"
        bin.install_symlink bin/"olympus" => "oly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/convergent-systems-co/olympus-cli/releases/download/v0.1.0/olympus_0.1.0_darwin_arm64.tar.gz"
      sha256 "658fb3644fbaf9845c8283b50ae350556ee4c9559f5fa9602e133e040a574764"

      define_method(:install) do
        bin.install "olympus"
        bin.install_symlink bin/"olympus" => "oly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/convergent-systems-co/olympus-cli/releases/download/v0.1.0/olympus_0.1.0_linux_amd64.tar.gz"
      sha256 "7db469a874840f942ada1fe93932c219e6f737726755622342d6039683e60b0b"
      define_method(:install) do
        bin.install "olympus"
        bin.install_symlink bin/"olympus" => "oly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/convergent-systems-co/olympus-cli/releases/download/v0.1.0/olympus_0.1.0_linux_arm64.tar.gz"
      sha256 "cb041277e980c018140c02039b3a95aadb4cff5190b54da6b81635b38851a076"
      define_method(:install) do
        bin.install "olympus"
        bin.install_symlink bin/"olympus" => "oly"
      end
    end
  end

  test do
    system "#{bin}/olympus", "--version"
  end
end
