# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ai < Formula
  desc "AI Constitution CLI — govern your AI assistant with a personal constitution"
  homepage "https://github.com/convergent-systems-co/aiConstitution"
  version "1.4.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.4.5/aiConstitution_1.4.5_darwin_amd64.tar.gz"
      sha256 "519877307d7709ddcf79d783226c2de031e981272029ff9d263a4e16d84b74f3"

      define_method(:install) do
        bin.install "ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.4.5/aiConstitution_1.4.5_darwin_arm64.tar.gz"
      sha256 "05ef43b0c17521eb700c24a683df3963810aab3d01510873df0051218053fcde"

      define_method(:install) do
        bin.install "ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.4.5/aiConstitution_1.4.5_linux_amd64.tar.gz"
      sha256 "8d060b0b609d9c3205563f0fc193f8b253bb54847007c3d454b0cb3558dfb177"
      define_method(:install) do
        bin.install "ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.4.5/aiConstitution_1.4.5_linux_arm64.tar.gz"
      sha256 "4146cf1df75bac8a3485acd7c2332c05e208950ccdbb8732bd1540b90796a8fb"
      define_method(:install) do
        bin.install "ai"
      end
    end
  end

  def caveats
    <<~EOS
      The ai binary may be blocked by macOS Gatekeeper on first run.
      To clear the quarantine flag:

        xattr -d com.apple.quarantine "#{bin}/ai"

      Then run: ai doctor
    EOS
  end

  test do
    system "#{bin}/ai", "version"
  end
end
