# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ai < Formula
  desc "AI Constitution CLI — govern your AI assistant with a personal constitution"
  homepage "https://github.com/convergent-systems-co/aiConstitution"
  version "1.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.1.1/aiConstitution_1.1.1_darwin_amd64.tar.gz"
      sha256 "23ab2d4b8ecbb72818951ebc0831570c25f25b05f6f6520c0670ef4a1455dd22"

      define_method(:install) do
        bin.install "ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.1.1/aiConstitution_1.1.1_darwin_arm64.tar.gz"
      sha256 "5bb71c72c45734ce8102aabf01d77c21d7844b33ee54fce1332696b0f1d15d8a"

      define_method(:install) do
        bin.install "ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.1.1/aiConstitution_1.1.1_linux_amd64.tar.gz"
      sha256 "cc142c699cc6fafea646995fecade6e6a989e4eb6c28d08161fc81f5f858dc6f"
      define_method(:install) do
        bin.install "ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.1.1/aiConstitution_1.1.1_linux_arm64.tar.gz"
      sha256 "f18103766ed1c4a3250f4a813f78e0928ecc646896af1711fa7318e0d3df9a7b"
      define_method(:install) do
        bin.install "ai"
      end
    end
  end

  def caveats
    <<~EOS
      The ai binary may be blocked by macOS Gatekeeper on first run.
      To clear the quarantine flag:

        xattr -d com.apple.quarantine "#{bin}/ai"

      Then run: ai doctor
    EOS
  end

  test do
    system "#{bin}/ai", "version"
  end
end
