# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ai < Formula
  desc "AI Constitution CLI — govern your AI assistant with a personal constitution"
  homepage "https://github.com/convergent-systems-co/aiConstitution"
  version "1.3.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.3.2/aiConstitution_1.3.2_darwin_amd64.tar.gz"
      sha256 "d56243df05cce1f084ebf4b416d6645fc2632077d7fe7c3d3a9dbb9d3ebf88b5"

      define_method(:install) do
        bin.install "ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.3.2/aiConstitution_1.3.2_darwin_arm64.tar.gz"
      sha256 "89391b6dcbb4f85c39361e26a3b5dc8a96d5df82ba05a18d283bdf717770c1dc"

      define_method(:install) do
        bin.install "ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.3.2/aiConstitution_1.3.2_linux_amd64.tar.gz"
      sha256 "de4fc043f60dabb347a17f5ae372c37bf1293f27f047b453c0c58d8ddbf10bbc"
      define_method(:install) do
        bin.install "ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.3.2/aiConstitution_1.3.2_linux_arm64.tar.gz"
      sha256 "861fd8c7f063d73b537826f63eccf01f075d069887a42fc1438d1f022c3abf2a"
      define_method(:install) do
        bin.install "ai"
      end
    end
  end

  def caveats
    <<~EOS
      The ai binary may be blocked by macOS Gatekeeper on first run.
      To clear the quarantine flag:

        xattr -d com.apple.quarantine "#{bin}/ai"

      Then run: ai doctor
    EOS
  end

  test do
    system "#{bin}/ai", "version"
  end
end
