# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atoms < Formula
  desc "AI Constitution CLI — govern your AI assistant with a personal constitution"
  homepage "https://github.com/convergent-systems-co/aiConstitution"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.0.0/aiConstitution_1.0.0_darwin_amd64.tar.gz"
      sha256 "a70bc5436f1321eb57d2e7a6ae623d3dc25093b9f5d1ea5fc11c8316ab131926"

      define_method(:install) do
        bin.install "ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.0.0/aiConstitution_1.0.0_darwin_arm64.tar.gz"
      sha256 "629d060f478bc03d38ec674aa7b19c80846aa60eb86651544b197d86adb8d2e1"

      define_method(:install) do
        bin.install "ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.0.0/aiConstitution_1.0.0_linux_amd64.tar.gz"
      sha256 "b2d33e94d66db8dd6777e0bf80dc4e412938a9c008c8010528019dbb11f1203e"
      define_method(:install) do
        bin.install "ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.0.0/aiConstitution_1.0.0_linux_arm64.tar.gz"
      sha256 "cc5c3b67b385484d4460bfde961e25d5cc575357ccb26bf65ddc6036a6a6bf12"
      define_method(:install) do
        bin.install "ai"
      end
    end
  end

  def caveats
    <<~EOS
      The ai binary may be blocked by macOS Gatekeeper on first run.
      To clear the quarantine flag:

        xattr -d com.apple.quarantine "#{bin}/ai"

      Then run: ai doctor
    EOS
  end

  test do
    system "#{bin}/ai", "version"
  end
end
