# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atoms < Formula
  desc "AI Constitution CLI — govern your AI assistant with a personal constitution"
  homepage "https://github.com/convergent-systems-co/aiConstitution"
  version "1.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.0.1/aiConstitution_1.0.1_darwin_amd64.tar.gz"
      sha256 "91e0d3297ab8f4e98593ead098cbf8504235b0d5c29f32b2658babff7651fad6"

      define_method(:install) do
        bin.install "ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.0.1/aiConstitution_1.0.1_darwin_arm64.tar.gz"
      sha256 "7e1ee30d6f47bbf95c0b3b7880adfbba8820c75113f79a7105063edcf9616c6c"

      define_method(:install) do
        bin.install "ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.0.1/aiConstitution_1.0.1_linux_amd64.tar.gz"
      sha256 "27bae907c4acd14e5049e68d57750c9e7c13dd3a35ea5d02f195b9c6ea34cec8"
      define_method(:install) do
        bin.install "ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.0.1/aiConstitution_1.0.1_linux_arm64.tar.gz"
      sha256 "4a404e4597d81ec7ad001523a8cddae1ea5ba0c5a7f41add446298107bfe71b9"
      define_method(:install) do
        bin.install "ai"
      end
    end
  end

  def caveats
    <<~EOS
      The ai binary may be blocked by macOS Gatekeeper on first run.
      To clear the quarantine flag:

        xattr -d com.apple.quarantine "#{bin}/ai"

      Then run: ai doctor
    EOS
  end

  test do
    system "#{bin}/ai", "version"
  end
end
