# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atoms < Formula
  desc "AI Constitution CLI — govern your AI assistant with a personal constitution"
  homepage "https://github.com/convergent-systems-co/aiConstitution"
  version "1.0.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.0.3/aiConstitution_1.0.3_darwin_amd64.tar.gz"
      sha256 "3da48fcceed301523323aff7e9ef46e7961906f1fc70a51be788786745b810a9"

      define_method(:install) do
        bin.install "ai" => "atoms"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.0.3/aiConstitution_1.0.3_darwin_arm64.tar.gz"
      sha256 "fb93d442141f9c8dd1ae71ccf717c180315caed285b8621df03b09f7f6339071"

      define_method(:install) do
        bin.install "ai" => "atoms"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.0.3/aiConstitution_1.0.3_linux_amd64.tar.gz"
      sha256 "4276a8809117f10d4a7155f697f5021825c94ac9a9f69cfe67a296330edc7b1b"
      define_method(:install) do
        bin.install "ai" => "atoms"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/convergent-systems-co/aiConstitution/releases/download/v1.0.3/aiConstitution_1.0.3_linux_arm64.tar.gz"
      sha256 "6cca688eee71f6e9e8ca6efde2108f105a645e24fa33f9bf478d114e71feb01b"
      define_method(:install) do
        bin.install "ai" => "atoms"
      end
    end
  end

  def caveats
    <<~EOS
      The ai binary may be blocked by macOS Gatekeeper on first run.
      To clear the quarantine flag:

        xattr -d com.apple.quarantine "#{bin}/ai"

      Then run: ai doctor
    EOS
  end

  test do
    system "#{bin}/ai", "version"
  end
end
