# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AuthB2c < Formula
  desc "Per-site B2C auth setup: Google · GitHub · Microsoft · Apple → Supabase"
  homepage "https://github.com/convergent-systems-co/auth-b2c"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/convergent-systems-co/auth-b2c/releases/download/v0.1.0/auth-b2c_Darwin_x86_64.tar.gz"
      sha256 "18e8a851c3ed0c23ac42e08b3bf6da247d9746ce9b578d4271637661666d7b6d"
    end
    if Hardware::CPU.arm?
      url "https://github.com/convergent-systems-co/auth-b2c/releases/download/v0.1.0/auth-b2c_Darwin_arm64.tar.gz"
      sha256 "af83ef095cf693adbed5178e221d42e205f12062ffe51d5ea9506ab7c93e7bd2"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/convergent-systems-co/auth-b2c/releases/download/v0.1.0/auth-b2c_Linux_x86_64.tar.gz"
      sha256 "ba2ff13237fc541f2619d9db2954f3f17b17640057807012a3d429336c9d28c6"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/convergent-systems-co/auth-b2c/releases/download/v0.1.0/auth-b2c_Linux_arm64.tar.gz"
      sha256 "21f6fea0c2bfef41e8cc046e17d981fd2d105be15f88695b3e585703186a28d0"
    end
  end

  def install
    bin.install "auth-b2c"
  end

  test do
    system bin/"auth-b2c", "--version"
  end
end
