name: Test Formula

on:
  push:
    paths:
      - "Formula/**.rb"
  pull_request:
    paths:
      - "Formula/**.rb"

jobs:
  test:
    name: brew test-bot
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        run: brew install-bundler-gems

      - name: Tap this repo
        run: brew tap convergent-systems-co/tap "$(pwd)"

      - name: Run brew test-bot --only-cleanup-before
        run: brew test-bot --only-cleanup-before

      - name: Run brew test-bot --only-setup
        run: brew test-bot --only-setup

      - name: Run brew test-bot --only-tap-syntax
        run: brew test-bot --only-tap-syntax

      - name: Run brew test-bot --only-formulae
        if: github.event_name == 'pull_request'
        run: brew test-bot --only-formulae

      - name: Run brew test-bot --only-cleanup-after
        if: always()
        run: brew test-bot --only-cleanup-after
